import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { SolarLead } from '@/types/solar';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 30,
    borderBottom: '2pt solid #22c55e',
    paddingBottom: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#22c55e',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#666',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingVertical: 5,
  },
  label: {
    fontSize: 12,
    color: '#666',
  },
  value: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333',
  },
  highlight: {
    backgroundColor: '#f0fdf4',
    padding: 15,
    borderRadius: 5,
    marginVertical: 15,
  },
  highlightText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#22c55e',
    textAlign: 'center',
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    borderTop: '1pt solid #ddd',
    paddingTop: 10,
  },
  signatureLine: {
    borderTop: '1pt solid #333',
    width: 200,
    marginTop: 40,
  },
});

interface ProposalDocumentProps {
  data: SolarLead;
}

export function ProposalDocument({ data }: ProposalDocumentProps) {
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
    }).format(amount);
  };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Solar Proposal</Text>
          <Text style={styles.subtitle}>Generated by SolarClose</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Client Information</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Name:</Text>
            <Text style={styles.value}>{data.clientName || 'N/A'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Address:</Text>
            <Text style={styles.value}>{data.address || 'N/A'}</Text>
          </View>
        </View>

        <View style={styles.highlight}>
          <Text style={styles.highlightText}>
            {formatCurrency(data.twentyFiveYearSavings)}
          </Text>
          <Text style={{ fontSize: 12, textAlign: 'center', color: '#666', marginTop: 5 }}>
            Total 25-Year Savings
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>System Details</Text>
          <View style={styles.row}>
            <Text style={styles.label}>System Size:</Text>
            <Text style={styles.value}>{data.systemSizeKw} kW</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>System Cost:</Text>
            <Text style={styles.value}>{formatCurrency(data.systemCost)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Current Monthly Bill:</Text>
            <Text style={styles.value}>{formatCurrency(data.currentMonthlyBill)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Break-Even Year:</Text>
            <Text style={styles.value}>Year {data.breakEvenYear}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Agreement</Text>
          <Text style={{ fontSize: 10, color: '#666', marginBottom: 10 }}>
            By signing below, the client acknowledges the proposed solar system specifications
            and estimated savings calculations presented in this proposal.
          </Text>
          <View style={styles.signatureLine} />
          <Text style={{ fontSize: 10, color: '#666', marginTop: 5 }}>Client Signature</Text>
        </View>

        <View style={styles.footer}>
          <Text style={{ fontSize: 8, color: '#999', textAlign: 'center' }}>
            Generated on {new Date().toLocaleDateString()} | SolarClose ROI Calculator
          </Text>
        </View>
      </Page>
    </Document>
  );
}