'use client';

import { useState } from 'react';
import type { SolarLead } from '@/types/solar';

interface ExportButtonProps {
  data: SolarLead;
}

export function ExportButton({ data }: ExportButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const canExport = data.clientName.trim() && data.address.trim();

  const handleExport = async () => {
    if (!canExport) return;
    
    try {
      setIsGenerating(true);
      
      // Dynamic import of jsPDF
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();
      
      // Header
      doc.setFontSize(24);
      doc.setTextColor(255, 193, 7); // Gold color
      doc.text(data.companyName || 'SOLAR PROPOSAL', 20, 30);
      
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text('Generated by SolarClose', 20, 40);
      
      // Client Info
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text('Client Information', 20, 60);
      
      doc.setFontSize(12);
      doc.text(`Name: ${data.clientName}`, 20, 75);
      doc.text(`Address: ${data.address}`, 20, 85);
      
      // Highlight savings
      doc.setFillColor(255, 248, 220);
      doc.rect(20, 100, 170, 30, 'F');
      doc.setFontSize(20);
      doc.setTextColor(255, 193, 7);
      doc.text(`$${data.twentyFiveYearSavings.toLocaleString()}`, 105, 120, { align: 'center' });
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text('Total 25-Year Savings', 105, 127, { align: 'center' });
      
      // System Details
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text('System Details', 20, 150);
      
      doc.setFontSize(12);
      doc.text(`System Size: ${data.systemSizeKw} kW`, 20, 165);
      doc.text(`System Cost: $${data.systemCost.toLocaleString()}`, 20, 175);
      doc.text(`Current Monthly Bill: $${data.currentMonthlyBill}`, 20, 185);
      doc.text(`Break-Even Year: Year ${data.breakEvenYear}`, 20, 195);
      
      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated on ${new Date().toLocaleDateString()} | SolarClose ROI Calculator`, 105, 280, { align: 'center' });
      
      // Save PDF
      doc.save(`solar-proposal-${data.clientName}.pdf`);
    } catch (error) {
      console.error('Failed to generate PDF:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={isGenerating || !canExport}
      className="w-full bg-primary text-primary-foreground font-semibold py-4 sm:py-3 px-4 sm:px-6 rounded-lg hover:opacity-90 transition-opacity disabled:opacity-50 text-base sm:text-sm"
      title={!canExport ? 'Please enter client name and address first' : ''}
    >
      {isGenerating ? 'Generating...' : !canExport ? '📄 Export Proposal (Enter client info)' : '📄 Export Proposal'}
    </button>
  );
}